### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by Brianzhengca** [cptx032/boring#41]
hello, do you know where can I find the documentation for boring?

**Comment by cptx032** [comment]
Hi @Brianzhengca  !
Today I'm developing boring in personal projects, including things in the way that needs arises.
There is no documentation yet, but anyway I'm trying to keep an simple API, so I believe that, for a while
to look the examples code will help a little.
Today I'm working in the `work` branch. In github if you switch the branch to `work` you will see some screenshots/gifs in README
![image](https://user-images.githubusercontent.com/12432805/50904753-e456e900-13ff-11e9-8487-fd5a8c07d51e.png)
I'm available if you have any questions

**Comment by Brianzhengca** [comment]
ok thank you xD
